name: Generate and Upload Video
on:
  schedule:
    - cron: '0 14 * * *'  # 2:00 PM UTC
    - cron: '0 18 * * *'  # 6:00 PM UTC
  workflow_dispatch:  # Allows manual trigger for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install -r requirements.txt

      - name: Run video generator
        env:
          GEMINI_API_KEY_1: ${{ secrets.GEMINI_API_KEY_1 }}
          ELEVENLABS_API_KEY_1: ${{ secrets.ELEVENLABS_API_KEY_1 }}
          VOICE_ID_1: "pNInz6obpgDQGcFmaJgB"
          GEMINI_API_KEY_2: ${{ secrets.GEMINI_API_KEY_2 }}
          ELEVENLABS_API_KEY_2: ${{ secrets.ELEVENLABS_API_KEY_2 }}
          VOICE_ID_2: "pNInz6obpgDQGcFmaJgB"
          GEMINI_API_KEY_3: ${{ secrets.GEMINI_API_KEY_3 }}
          ELEVENLABS_API_KEY_3: ${{ secrets.ELEVENLABS_API_KEY_3 }}
          VOICE_ID_3: "pNInz6obpgDQGcFmaJgB"
          GEMINI_API_KEY_4: ${{ secrets.GEMINI_API_KEY_4 }}
          ELEVENLABS_API_KEY_4: ${{ secrets.ELEVENLABS_API_KEY_4 }}
          VOICE_ID_4: "pNInz6obpgDQGcFmaJgB"
          GEMINI_API_KEY_5: ${{ secrets.GEMINI_API_KEY_5 }}
          ELEVENLABS_API_KEY_5: ${{ secrets.ELEVENLABS_API_KEY_5 }}
          VOICE_ID_5: "pNInz6obpgDQGcFmaJgB"
          GEMINI_API_KEY_6: ${{ secrets.GEMINI_API_KEY_6 }}
          ELEVENLABS_API_KEY_6: ${{ secrets.ELEVENLABS_API_KEY_6 }}
          VOICE_ID_6: "pNInz6obpgDQGcFmaJgB"
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python main.py

      - name: Upload video artifact
        uses: actions/upload-artifact@v4  # Updated from v3 to v4
        with:
          name: final-video
          path: final_video.mp4